services:
  - type: web
    name: safetalk-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci
      npm run build
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: safetalk-app
          property: host
      - key: ASSET_URL
        fromService:
          type: web
          name: safetalk-app
          property: host
      - key: VITE_APP_URL
        fromService:
          type: web
          name: safetalk-app
          property: host
      - key: FORCE_HTTPS
        value: true
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: single
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.mailtrap.io
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        value: placeholder_username
      - key: MAIL_PASSWORD
        value: placeholder_password
      - key: MAIL_ENCRYPTION
        value: tls
      - key: STRIPE_SECRET
        value: sk_test_placeholder
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_placeholder